# Generated by Django 3.2.7 on 2021-11-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amigosApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
